### ISSUE TITLE
Make facet query case insensitive

### ISSUE THREAD

**Issue by usercluster** [ropensci/solrium#110]
Good afternoon,
I am trying to write a query that should return results that match a particular field with a string, but I would like this to be case insensitive. Here the example:

ls.tweets_query<- cli$facet(params = list(q='hashtags:londonbridge',
                                     facet.date='createdAt', 
                                     facet.date.include='all',
                                     facet.date.start='2017-03-01T00:00:00Z', 
                                     facet.date.end='2017-09-01T23:59:99.999Z', 
                                     facet.date.gap='+1HOUR'))

In this case, I would like in the results all those that match 'londonbridge', but also 'Londonbridge' and 'LondonBridge'. How can I do that? I was looking at the Lucerne syntax but was not able to figure it out how to solve it.
Thanks!

**Comment by sckott** [comment]
thanks for the question @usercluster 

I don't know off hand how to do that. Do you manage the Solr installation? If so, what version of Solr is it.
