### ISSUE TITLE
Can it handle multiple connections by pooling ?

### ISSUE THREAD

**Issue by abhik1368** [ropensci/solrium#120]
I wanted to know if the connection object can handle multiple database connections for one or more users just as like database pooling option with pool package ?

**Comment by sckott** [comment]
thx for your question. I assume you are talking about `SolrClient`?

if so, `SolrClient` is not a database connection object in the same sense as the DBI connection objects, that have a pointer and such. 

The idea with `SolrClient` is that each instance of it (e.g., `conn`) contains the connection information for each Solr instance, where you can call methods on the instance (e.g., `conn$facet`), or pass it through functions (e.g., `solr_facet(conn, ...)`)
