### ISSUE TITLE
Cannot delete by query

### ISSUE THREAD

**Issue by abhik1368** [ropensci/solrium#121]
httpcli$proxies <- proxy : object 'httpcli' not found 

Found the function 

`obj_POST <- function(base, path, body, args, proxy, ...) {
  invisible(match.arg(args$wt, c("xml", "json", "csv")))
  args <- lapply(args, function(x) if (is.logical(x)) tolower(x) else x)
  body <- jsonlite::toJSON(body, auto_unbox = TRUE)
  cli <- crul::HttpClient$new(
    url = base,
    headers = list(`Content-Type` = "application/json"),
    opts = list(...)
  )
  if (inherits(proxy, "proxy")) httpcli$proxies <- proxy
  tt <- cli$post(path, query = args, body = body, encode = "form", ...)
  get_response(tt)
}`

need to assign cli to httpcli or change httpcli to cli

**Comment by sckott** [comment]
thanks, fixed now
