### ISSUE TITLE
Not authenticating to Solr cloud when security enabled.

### ISSUE THREAD

**Issue by rob59** [ropensci/solrium#124]
solrium not able to connect and run a query against a password enabled Solr cloud.

Would it be possible to add to the Solr_GET, Solr_POST etc. functions in zzz.R the ability to send in an authentication string?
i.e.  auth = auth(user = "user", pwd = "pass") -  to the HttpClient request?

something like:-
solr_GET <- function(base, path, args, callopts = NULL, proxy = NULL, 
  progress = NULL, auth ) {

  cli <- crul::HttpClient$new(url = base, opts = callopts,  progress = progress, auth = auth)

And add an additional param to the solrClient function so it can take in the new auth values.

SolrClient$new(host = "192.168.1.43", path = "solr/efund/select", port = "8982", auth = list(user="xxx", pwd ="xxx")))

I think that would solve it?

Many thanks

<details> <summary><strong>Session Info</strong></summary>
Solr 8.5.2, 
Running zookeeper, 
Solr running in cloud mode, with security enabled.

Sorry devtools not working on my RStudio as running arm64 and devtools not yet comparable.
```
</details>

**Comment by sckott** [comment]
Thanks for the issue. 

(for session info you can always do `sessionInfo()` in base R)

Yeah i think we can add auth, will ping back here soon

**Comment by rob59** [comment]
Thanks Sckott, that would be so helpful! Thanks in advance and let me know if you need any testing done!

**Comment by rob59** [comment]
HI Sckott,  Is there any update on this or anything I can help test?

Many thanks

Rob.

**Comment by sckott** [comment]
@rob59 just pushed a change. try again. you can set auth in the SolrClient, then pass that to fxns, or call methods on the object. let me know

```r
SolrClient$new(auth = crul::auth(user = "hello", pwd = "world"))
```

**Comment by rob59** [comment]
Hi Sckott,

Many thanks, I pulled down the latest code and ran a simple R script, but im obviously doing something silly as getting the below error message:-

(cli <- SolrClient$new(host = "192.168.1.43", path = "solr/efund/select", port = "8982", auth = crul::auth(user = "xx", pwd = "xx")))
Error in initialize(...) : 
  unused argument (auth = crul::auth(user = "xx", pwd = "xx"))

Any suggestions as to what I have got wrong?

Rob.

**Comment by rob59** [comment]
A bit more testing and details:-


R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: aarch64-unknown-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Workspace loaded from ~/.RData]

> install.packages("solrium")
Error in install.packages : Updating loaded packages
Warning message:
Character set is not UTF-8; please change your locale 
> install.packages("solrium")
Installing package into '/home/rstudio/R/aarch64-unknown-linux-gnu-library/3.6'
(as 'lib' is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/solrium_1.2.0.tar.gz'
Content type 'application/x-gzip' length 179892 bytes (175 KB)
==================================================
downloaded 175 KB

* installing *source* package 'solrium' ...
** package 'solrium' successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (solrium)

The downloaded source packages are in
	'/tmp/Rtmpa1PnGk/downloaded_packages'
> library(httr)
> library(crul)

Attaching package: 'crul'

The following object is masked from 'package:httr':

    handle

> library(solrium)
> cli <- SolrClient$new(host = "192.168.1.43", path = "solr/efund/select", port = "8982", auth = crul::auth(user = "xx", pwd = "xx"))
Error in initialize(...) : 
  unused argument (auth = crul::auth(user = "xx", pwd = "xx"))
> library(solrium)
> SolrClient$new(host = "192.168.1.43", path = "solr/efund/select")
<Solr Client>
  host: 192.168.1.43
  path: solr/efund/select
  port: 8983
  scheme: http
  errors: simple
  proxy:
> packageVersion("solrium")
[1] '1.2.0'
> SolrClient$new(auth = crul::auth(user = "hello", pwd = "world"))
Error in initialize(...) : 
  unused argument (auth = crul::auth(user = "hello", pwd = "world"))
>

**Comment by sckott** [comment]
Sorry, I should have said to update from here on GitHub. You can do that like 

```r
install.packages("pak")
pak::pkg_install("ropensci/solrium")
```

an alternative to `pak` is the package `remotes`. up to you

**Comment by rob59** [comment]
Hi Sckott,

No not at all, my fault for not knowing more about how to do these things!  
( I ended up using the remotes method as running studio on a raspberry pi 4 and "pak" didn't want to compile for some reason.)

I am pleased to report its all working and authenticating well, thank you very very much! Great job!


> (cli <- SolrClient$new(host = "192.168.1.43", path = "solr/xyzzy/select", port = "8982", auth = crul::auth(user = "xx", pwd = "xx")))
<Solr Client>
  host: 192.168.1.43
  path: solr/xyzzy/select
  port: 8982
  scheme: http
  errors: simple
  userpwd: ********
  proxy:
> res <- cli$search(params = list(q = '*:*', rows = "100"))
> #convert a string into a date
> res$Time <- as.Date(res$Time)
> data_ts <- xts(res$Electricity__pounds_, res$Time)        # Convert data frame to time series
> data_ts                                      # Print time series
           [,1]
2017-01-01 2.94
2017-01-02 2.86
2017-01-03 2.67
2017-01-04 2.75
2017-01-05 2.56

**Comment by sckott** [comment]
@rob59 great! glad its working
