### ISSUE TITLE
Support for queries using the join plugin

### ISSUE THREAD

**Issue by sckott** [ropensci/solrium#69]
if needed in this client, don't know yet 

docs:  https://wiki.apache.org/solr/Join

**Comment by joelgombin** [comment]
Is that still in the pipe?

**Comment by sckott** [comment]
I've never used it. do yo use the feature?  if it's easy enough to include can do it

**Comment by joelgombin** [comment]
I don't have a ton of experience with solr, but I currently have a usecase where it looks like join would be useful. It looks something like:

```r
test <- map2_df(seq(1, length(urls), by = 100), 
                          seq(100, length(urls)+100, by = 100), 
                          ~ solr_search(q = paste0('id:(', paste0('"', urls[.x:.y], '"', collapse = ","), ")"), 
                                                 fl=c("id", "url", "naked_titre"), 
                                                 wt = "csv", 
                                                 rows = 101))
```

where `urls` is a vector of length 1200+ (but could be much longer). I cant' just pass it at once in the request since its size is limited. So this is deeply inefficient, and I believe join is the answer to this kind of situation. Am I undestanding this correctly?

**Comment by joelgombin** [comment]
Although on second thought, implementing the solr_search as a GET request to the API rather than through query parameters passed in the URL may be a better and simplier strategy, at least in my usecase. See http://yonik.com/solr-json-request-api/

**Comment by joelgombin** [comment]
So, with a bit more thought put into it, GET is not going to help us, but POST might, right?

**Comment by sckott** [comment]
thanks for the details - off on weekend vacation - get to this next week

**Comment by sckott** [comment]
Okay, so two issues here: 

- GET vs. POST - with GET you can hit up upon a HTTP 414 URL too long error i think after about 4000 characters. So solution would be to use POST request and pass query in the body, which has no limit. Problem is we don't allow user to toggle between GET and POST right now, but planning to do so as part of an overhaul of the pkg  (see #99 and #100 )
- joins: I'm not quite sure joins are what you are looking for. if you see the egs on that page, they are about matching from field 1 to field 2 with `from` and `to` params that match across documents. is that what you're looking to do?

**Comment by joelgombin** [comment]
If I can use POST that will be fine !

Le mer. 2 août 2017 20:45, Scott Chamberlain <notifications@github.com> a
écrit :

**Comment by sckott** [comment]
@joelgombin reinstall `devtools::install_github("ropensci/solrium")` and try again, it's a rework of the pkg, so do read the docs
