### ISSUE TITLE
Adding support for facet.pivot argument

### ISSUE THREAD

**Issue by ReportMort** [ropensci/solrium#80]
I've been looking for something that would return counts by grouped by multiple document fields and it wasn't obvious how to do that in the package. 

I looked at the documentation at https://wiki.apache.org/solr/SimpleFacetParameters and facet.pivot seemed to be the right tool, but it's not an available function argument to `solr_facet`. Can this functionality be supported in the package?

**Comment by sckott** [comment]
Thanks for the issue. That looks interesting. I'll have a look at the PR

**Comment by sckott** [comment]
did #81 sort this out? or more to do?

**Comment by ReportMort** [comment]
I think that works. Thanks for the timely response.

**Comment by pemorris** [comment]
Dear Scott and Steve, 

Many thanks for building some fact pivot capability into Solrium, this is very exciting. 

I realize you are developing against SOLR 5.x so does this mean that the pivot facet option would not work with a SOLR 4.9 instance? Unfortunately we are stuck with SOLR 4.9 but we would still be very interested in querying/faceting through Solrium.

Thanks again for some amazing work, 

Paul

**Comment by ReportMort** [comment]
@pemorris I'm querying against a Solr4.10.1 instance and it seems to be working. I believe facet.pivot has been around since Solr4.0 (it says that [here] (https://wiki.apache.org/solr/SimpleFacetParameters#facet.pivot)) and I see it's in the 4.9 documentation available [here] (https://archive.apache.org/dist/lucene/solr/ref-guide/apache-solr-ref-guide-4.9.pdf), so you should be able to take advantage.

**Comment by sckott** [comment]
Thanks for dropping by @pemorris  Looks like pivot should work for you as @ReportMort said.  Can you try and see if it does?

I think there definitely are things that aren't < 5 compatible. Some Solr folks I talked to said most are moving to 5+, so I started to move to 5+. I think the Solr management stuff (e.g, cores, collections) might be a problem, but I'm hoping that the query functions (e.g, `solr_search`, `solr_facet`) will still work fine.  Plz do open up new issues if there's things that don't work in your version

**Comment by pemorris** [comment]
Hi Scott, thanks for the reply. I know facet pivoting has been around for a while, but it looked from one of Yonik's posts that a lot of facet updates had changed in 5.x and I know you are developing against 5.x. 

I will definitely give your latest pivot facet changes a go today and report back to yourself and Steve. 

Sorry to interrupt the discussion, but it is great what you are doing! 

Paul

**Comment by pemorris** [comment]
Hi Scott, 

I've downloaded the latest build of Solrium and everything looks very encouraging, thanks for the very useful new feature. The following facet pivot appears to be working, but shouldn't counts be returned for both fields?

Apologies if I have missed something in the way pivot facets work, but the counts are returned for both pivot fields when I do a direct URL (http://localhost:8983/solr/query?q=silicon&description=on&facet=true&facet.limit=3&facet.pivot=Name,Inst) 

The equivalent Solrium output is enclosed below, and the counts shown are just for the second field 

solr_facet(q=silicon,facet.limit=3,base=url,facet.pivot='Name,Inst')

   Name   Inst  count
  (chr)   (chr) (int)
1 "NameA" FirmA    54
2 "NameB" FirmB    35
3 "NameC" FirmC    34

Thanks again, 

Paul

**Comment by ReportMort** [comment]
I think that was a poor judgement on my part to assume the user would only want the count data for the lowest level of granularity (Name and Inst in your case). Does it make sense to return list of data.frames with 1 data.frame per level? (see below for example).

```
solr_facet(q=silicon,facet.limit=3,base=url,facet.pivot='Name,Inst')
[[1]]
   Name count
1 NameA   300
2 NameB   200
3 NameC   100

[[2]]
   Name  Inst count
1 NameA FirmA    54
2 NameB FirmB    35
3 NameC FirmC    34
```

**Comment by pemorris** [comment]
Dear Scott and Steve, I feel slightly bad bringing this up, but having the counts for both pivot levels would be very useful. Please let me know if we can help in any way. 

What you have done already is still excellent. 

Thanks again, 

Paul

**Comment by sckott** [comment]
@pemorris don't feel bad!  Looks like @ReportMort has a fix on his branch

@ReportMort that sounds good to have a list, ideally named though

**Comment by ReportMort** [comment]
Thanks guys. Here is an example of what I've got returning now. I'll open a PR.

```
solr_facet(q=silicon,facet.limit=3,base=url,facet.pivot='Name,Inst')

facet$pivot
facet$pivot$Name
   Name count
1 NameA   300
2 NameB   200
3 NameC   100

facet$pivot$`Name,Inst`
   Name  Inst count
1 NameA FirmA    54
2 NameB FirmB    35
3 NameC FirmC    34
```

**Comment by sckott** [comment]
thanks, looks good

**Comment by pemorris** [comment]
The suggested approach looks great, thanks for looking at this guys, fantastic. Paul

**Comment by pemorris** [comment]
Just tried the new build and everything works perfectly ... thanks again for this great feature, it is incredibly useful. 

Paul

**Comment by sckott** [comment]
closing, I think this is sorted
