### ISSUE TITLE
Pivot facets

### ISSUE THREAD

**Issue by VadymBoikov** [ropensci/solrium#91]
Hi!
Can you add support of Solr pivotting ?

https://lucidworks.com/blog/2014/10/03/pivot-facets-inside-and-out/

Thank you in advance

**Comment by sckott** [comment]
Thanks, I'll get it done soon

**Comment by sckott** [comment]
@VadymBoikov  You can already use pivot for Solr servers that support it, because we pass on additional solr params via `...` because sometimes we can't predict all solr params

```r
solr_connect('http://api.plos.org/search')
solr_facet(facet.pivot = "journal,subject", facet.limit =  3)
```

```r
#> $facet_queries
#> NULL
#> 
#> $facet_fields
#> NULL
#> 
#> $facet_pivot
#> $facet_pivot$journal
#>          journal   count
#> 1       plos one 1334916
#> 2  plos genetics   52417
#> 3 plos pathogens   45565
#> 
#> $facet_pivot$`journal,subject`
#>          journal                       subject   count
#> 1       plos one     biology and life sciences 1253012
#> 2       plos one  medicine and health sciences  978834
#> 3       plos one research and analysis methods  833704
#> 4  plos genetics     biology and life sciences   50828
#> 5  plos genetics                      genetics   44291
#> 6  plos genetics research and analysis methods   39784
#> 7 plos pathogens     biology and life sciences   43989
#> 8 plos pathogens  medicine and health sciences   39851
#> 9 plos pathogens                     organisms   34348
#> 
#> 
#> $facet_dates
#> NULL
#> 
#> $facet_ranges
#> NULL
```

I'll add the parameters explicitly though

**Comment by sckott** [comment]
ahhh, we already support pivots https://github.com/ropensci/solrium/blob/master/R/solr_facet.r#L83 

but the internal parsing isn't working, as you can't pass in a vector like `c('journal', 'subject')` as  you should be able tod

**Comment by sckott** [comment]
@VadymBoikov added a few more examples of usage https://github.com/ropensci/solrium/blob/master/R/solr_facet.r#L27-L33 

anything else to do?

**Comment by VadymBoikov** [comment]
@sckott , that's what I need. Thank you!

**Comment by sckott** [comment]
great, txh
