### ISSUE TITLE
Echo the actual URL sent to Solr

### ISSUE THREAD

**Issue by rizwaan** [ropensci/solrium#93]
Please add functionality to view the actual url being sent to Solr. Will be a great help while debugging.

**Comment by sckott** [comment]
what function calls? all? or just certain ones?

The url should be printed to screen as a message, e.,g 

```r
library("solrium")
solr_connect('http://api.plos.org/search')
solr_search(q='*:*', rows=2, fl='id')
#> http://api.plos.org/search?q=*:*&rows=2&fl=id&wt=json
#> # A tibble: 2 × 1
#>                                      id
#>                                   <chr>
#> 1    10.1371/journal.pone.0104701/title
#> 2 10.1371/journal.pone.0104701/abstract
```

the first line in the output above is a the URL of the request. it can be suppressed by being wrapped in `suppressMessages()` call

are you not seeing that URL printed?

**Comment by rizwaan** [comment]
Attaching a screenshot for reference.
I am using solr_search function which gives the results but wont echo the actual url sent.

![image](https://cloud.githubusercontent.com/assets/7242395/18194277/12b881bc-7102-11e6-8c39-ff5028b5c877.png)

**Comment by sckott** [comment]
I think you might be globally supressing messages

**Comment by rizwaan** [comment]
Thanks for the suggestion Scott.
Warning level was set to default (0). Switched it to 1 to grab all messages. However the actual URL is still not displayed.

![image](https://cloud.githubusercontent.com/assets/7242395/18196362/88fde2f2-710e-11e6-9631-5e8dddec4ab8.png)

**Comment by sckott** [comment]
Try this `solr_search(q='*:*', rows=2, fl='id', callopts = httr::verbose())`

**Comment by rizwaan** [comment]
Thanks Scott.. that worked.

**Comment by sckott** [comment]
glad it worked. as I can't reproduce your problem with the URL not printing on the function call, I'll close for now
