### ISSUE TITLE
Atomic Update

### ISSUE THREAD

**Issue by yinghaoh** [ropensci/solrium#97]
Hi, does this package support solr atomic update? Not sure how to do it in R

**Comment by sckott** [comment]
thanks for your question @yinghaoh - i'll get back to you soon

**Comment by sckott** [comment]
@yinghaoh you're talking about the atomic update listed here https://cwiki.apache.org/confluence/display/solr/Updating+Parts+of+Documents - any interest in   optimistic concurrency  type or just atomic type?

**Comment by yinghaoh** [comment]
I think just atomic type. I ended up using curl to post the document.
Thanks a lot anyway.

Yinghao

On Tue, Jan 31, 2017 at 7:23 PM, Scott Chamberlain <notifications@github.com

**Comment by sckott** [comment]
@yinghaoh Okay, I just added two functions `update_atomic_xml` and `update_atomic_json` if you want to try those

**Comment by yinghaoh** [comment]
Sure. thanks a lot.

**Comment by sckott** [comment]
@yinghaoh did those fxns work for you?
