### ISSUE TITLE
GET request problem

### ISSUE THREAD

**Issue by ZZZZh** [ropensci/solrium#99]
Thanks for contributing this awesome package!
It seems there's some problem with get request. The length of fq I used is huge with more than 100 ORs and I received errors listed bellow. Is it possible to amend POST request into solrium so that it could be solved. Thank you!
![_20170626184729](https://user-images.githubusercontent.com/11428907/27536055-f1738bc2-5a9f-11e7-8e40-c5be97bc62a9.jpg)
![_20170626184732](https://user-images.githubusercontent.com/11428907/27536056-f17d4db0-5a9f-11e7-80cd-3c4b0f0afa10.jpg)

**Comment by ZZZZh** [comment]
I've checked that Get request works with less than around 100 ORs.

**Comment by sckott** [comment]
thanks for opening the issue. 

Can you share your R session info, paste in results from `sessinInfo()` in a code block 

also what fxn are you using? `solr_search`? 

looks like POST is supported for that, so can try adding that

**Comment by ZZZZh** [comment]
Problem occurs at `solr_search(q = niubi[[j]]$queryText, fq = fq, fl = niubi[[j]]$returnSearchNames, 
    row = 1, sort = sda, raw = T) 
`
Here's the error including traceback:
```
Error in if (grepl("html", x$headers$`content-type`)) { : 
  argument is of length zero 
5. solr_error(tt) 
4. solr_GET(handle_url(conn, name), args, callopts, conn$proxy) 
3. structure(solr_GET(handle_url(conn, name), args, callopts, conn$proxy), 
    class = "sr_search", wt = wt) 
2. solr_search(q = niubi[[j]]$queryText, fq = fq, fl = niubi[[j]]$returnSearchNames, 
    row = 1, sort = sda, raw = T) 
1. simple3(niubi) 
In addition: Warning message:
package ‘stringr’ was built under R version 3.2.3 

```
where `simple3` is my wrapped function and `solr_search` is the problem line. Traceback 3,4,5 seems the functions in solrium.
Thank you in advance.

**Comment by sckott** [comment]
thanks i'll have a look soon

**Comment by sckott** [comment]
hmm, we don't really have the functions setup to toggle between GET or POST HTTP methods, like e.g., the Ruby client does

```ruby
solr.music :params => {:q => "*:*"}
# vs.
solr.music :data => {:q => "*:*"}
```

Trying to just use a parameter to let user pick GET vs. POST, but e.g, some Solr instances may require an API key that has to be passed as a query parameter, not in the body. So it's a bit complicated. 

see also #100

**Comment by ZZZZh** [comment]
I see. Take your time. I'm deeply grateful for your support and looking forward to your good news .

**Comment by sckott** [comment]
@ZZZZh reinstall `devtools::install_github("ropensci/solrium")` and try again, it's a rework of the pkg, so do read the docs
